### PR TITLE
Added am-fm decomposition for 1d images to tools

### PR DESCRIPTION
**Pull request by alvarouc**
Added am-fm decomposition as described in [1] 
run amfm1d.py to see demo results. 

[1] Bovik, Alan C. Handbook of image and video processing. Academic press, 2010.

### CODE REVIEW

**Comment by rdevon** [comment]
OK, thanks for adding this. Let me deal with it tomorrow: I want to clean it up a bit and change the functioning of "main". Really if we're plotting it should be an option from argparse such that you could do:
python amfm1d.py some_args --plot  
or something. The primary function though should be as a preprocessor for deep learning models. If you have a dataset somewhere I can play with, I can work on adding the EEG dataset class and importer, and then attach this to the EEG dataset class constructor.
Thanks btw. I'll probably merge tomorrow after I make comments.

**Comment by alvarouc** [comment]
I don't have raw datasets. I will ask around

Are you planning to feed raw EEG?
I don't recommend feeding raw EEG data because the pre-processing steps are not standard yet. What I believe we should do is to do a more generic class where we can feed time series data from various channels.

**Comment by rdevon** [comment]
No it wont be the standard way; rather it will be an option among other (standard) preprocessing steps. I assume that AM-FM shouldn't be used in conjunction with other preprocessing steps. The question is: what steps can be used together and what can't? We want the data being fed into the EEG dataset class to be as general as possible, so that the user can decide what preprocessing to use when attempting different models.
What I have in mind is this:
The importer (like mri_utils) takes various formats of NI EEG data and converts into numpy format along with various other information (labels, whatever else we think they'll need). 
The EEG dataset class does various preprocessing as per user specification.

I might be wrong though as I've never used EEG before so I need your help understanding the formats available, etc. But mostly I'm thinking along the lines of the MRI class.

I'll probably start the EEG class today so we can work on it in parallel.

**Comment by rdevon** [comment]
Is the EEG data sparse or dense?

**Comment by alvarouc** [comment]
EEG is dense. You might want to look at EEGLAB
http://sccn.ucsd.edu/eeglab/

**Comment by rdevon** [comment]
Could you describe the typical processing steps with EEG, using that software or otherwise? What data do we typically get before applying it to a model?

**Comment by rdevon** [comment]
OK, I'm merging, then cleaning. Look at my changes after I make them: it'll give some guides for format / etc.

**Pull request merged**
